"last_directory": "entechlab/hvac/labeler_tasks/submissions/src/images/"
"last_import_directory": "entechlab/hvac/labeler_tasks/backup/"
"label_colors_file": "entechlab/examples/annotations/label_colors.txt"
